# Root package
packages:
  - '.'  # This points to the root directory

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
